# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-03-10 20:34:12
# AutoCoder System - Automated Code Generation

import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.patches import FancyBboxPatch
import numpy as np

print("Creating graphical Hello World display...")

# Create figure with dark background
fig, ax = plt.subplots(figsize=(12, 7))
fig.patch.set_facecolor('#0a0a2e')
ax.set_facecolor('#0a0a2e')

# Set axis limits
ax.set_xlim(0, 10)
ax.set_ylim(0, 7)
ax.axis('off')

# Draw decorative background circles (glow effect)
for i in range(5, 0, -1):
    circle = plt.Circle((5, 3.5), i * 0.8,
                         color='#1a1a6e',
                         alpha=0.15,
                         zorder=1)
    ax.add_patch(circle)

# Draw a glowing rectangle behind the text
fancy_box = FancyBboxPatch((0.5, 2.2), 9, 2.6,
                            boxstyle="round,pad=0.1",
                            linewidth=3,
                            edgecolor='#00d4ff',
                            facecolor='#050520',
                            alpha=0.85,
                            zorder=2)
ax.add_patch(fancy_box)

# Add outer glow border
fancy_box_glow = FancyBboxPatch((0.3, 2.0), 9.4, 3.0,
                                 boxstyle="round,pad=0.1",
                                 linewidth=1,
                                 edgecolor='#0066ff',
                                 facecolor='none',
                                 alpha=0.4,
                                 zorder=2)
ax.add_patch(fancy_box_glow)

# Main "HELLO WORLD" text with letter spacing simulation
hello_text = ' '.join(list('HELLO WORLD'))

# Shadow/glow layer
ax.text(5.06, 3.44, hello_text,
        fontsize=52,
        fontweight='bold',
        color='#0033cc',
        ha='center',
        va='center',
        fontfamily='monospace',
        alpha=0.6,
        zorder=3)

# Main text
ax.text(5, 3.5, hello_text,
        fontsize=52,
        fontweight='bold',
        color='#00d4ff',
        ha='center',
        va='center',
        fontfamily='monospace',
        zorder=4)

# Subtitle
subtitle = ' '.join(list('Graphical Display'))
ax.text(5, 2.55, subtitle,
        fontsize=16,
        color='#88aaff',
        ha='center',
        va='center',
        fontfamily='monospace',
        style='italic',
        zorder=4)

# Decorative stars
np.random.seed(42)
star_x = np.random.uniform(0.1, 9.9, 80)
star_y = np.concatenate([
    np.random.uniform(0.1, 2.0, 40),
    np.random.uniform(5.1, 6.9, 40)
])
star_sizes = np.random.uniform(5, 40, 80)
star_alpha = np.random.uniform(0.3, 1.0, 80)

ax.scatter(star_x, star_y, s=star_sizes,
           c='white', alpha=star_alpha,
           zorder=1, marker='*')

# Decorative horizontal lines
for y_pos, alpha_val in [(2.1, 0.8), (4.9, 0.8), (2.05, 0.3), (4.95, 0.3)]:
    ax.plot([0.5, 9.5], [y_pos, y_pos],
            color='#00d4ff',
            linewidth=1.5 if alpha_val > 0.5 else 0.5,
            alpha=alpha_val,
            zorder=3)

# Corner decorations
corners = [(0.5, 2.1), (9.5, 2.1), (0.5, 4.9), (9.5, 4.9)]
for cx, cy in corners:
    ax.plot(cx, cy, 'o', color='#00d4ff', markersize=8, zorder=5)
    ax.plot(cx, cy, 'o', color='white', markersize=3, zorder=6)

# Title at top
title_text = ' '.join(list('* NOVA ASSISTANT *'))
ax.text(5, 6.3, title_text,
        fontsize=14,
        color='#ffaa00',
        ha='center',
        va='center',
        fontfamily='monospace',
        fontweight='bold',
        zorder=4)

# Bottom label
ax.text(5, 0.4, 'Python  |  Matplotlib  |  2026',
        fontsize=10,
        color='#445577',
        ha='center',
        va='center',
        fontfamily='monospace',
        zorder=4)

plt.subplots_adjust(left=0.02, right=0.98, top=0.98, bottom=0.02)

print("Displaying graphical Hello World...")
plt.savefig('hello_world_graphic.png', dpi=150,
            bbox_inches='tight',
            facecolor='#0a0a2e')
print("Saved as 'hello_world_graphic.png'")
plt.show()
print("Done!")