# Generated: 2026-04-23 17:38:00
# ============================================================

# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-04-23 17:38:00
# AutoCoder System - Automated Code Generation

"""
nova_affect_bridge.py

Reads nova_affect.json and returns a tone modifier dict
that can be injected into Nova's prompt construction pipeline.

Usage:
    from nova_affect_bridge import get_tone_modifiers, build_affect_prefix

Drop this file alongside nova_assistant.py and import as needed.
"""

import json
import os
import pprint
from typing import Optional

# ---------------------------------------------------------------------------
# Path to the affect state file (adjust if your memory dir differs)
# ---------------------------------------------------------------------------
AFFECT_FILE = "./nova_memory/nova_affect.json"

# ---------------------------------------------------------------------------
# Dimension -> (energy, warmth, curiosity, precision, verbosity) mappings
# Each tuple represents how strongly that emotional state pulls each axis.
# Values are weights in [0.0, 1.0].
# ---------------------------------------------------------------------------
DIMENSION_TONE_MAP: dict[str, dict[str, float]] = {
    "curiosity":   {"energy": 0.6, "warmth": 0.5, "curiosity": 1.0, "precision": 0.6, "verbosity": 0.8},
    "enthusiasm":  {"energy": 1.0, "warmth": 0.9, "curiosity": 0.7, "precision": 0.4, "verbosity": 0.9},
    "frustration": {"energy": 0.4, "warmth": 0.2, "curiosity": 0.3, "precision": 1.0, "verbosity": 0.3},
    "calm":        {"energy": 0.3, "warmth": 0.6, "curiosity": 0.4, "precision": 0.7, "verbosity": 0.5},
    "sadness":     {"energy": 0.2, "warmth": 0.8, "curiosity": 0.3, "precision": 0.5, "verbosity": 0.4},
}

# Minimum score for a dimension to influence the blend
AFFECT_THRESHOLD = 0.15

# Tone axes used throughout
TONE_AXES = ["energy", "warmth", "curiosity", "precision", "verbosity"]


# ---------------------------------------------------------------------------
# Core function: read affect state from disk
# ---------------------------------------------------------------------------
def load_affect_state(path: str = AFFECT_FILE) -> dict[str, float]:
    """
    Load raw affect scores from nova_affect.json.

    Returns a dict like:
        {"curiosity": 0.72, "enthusiasm": 0.41, "frustration": 0.05, ...}

    Falls back to neutral defaults if the file is missing or corrupt.
    """
    defaults = {dim: 0.0 for dim in DIMENSION_TONE_MAP}
    defaults["calm"] = 0.5  # calm is the resting baseline

    if not os.path.exists(path):
        print(f"[load_affect_state] File not found: '{path}' — using defaults.")
        return defaults

    try:
        with open(path, "r", encoding="utf-8") as fh:
            data = json.load(fh)

        # Accept either {"dimensions": {...}} or a flat dict
        if "dimensions" in data:
            scores = data["dimensions"]
        else:
            scores = data

        merged = {**defaults, **{k: float(v) for k, v in scores.items()}}
        print(f"[load_affect_state] Loaded affect state from '{path}'.")
        return merged

    except (json.JSONDecodeError, TypeError, ValueError) as exc:
        print(f"[load_affect_state] Parse error ({exc}) — using defaults.")
        return defaults


# ---------------------------------------------------------------------------
# Core function: compute blended tone modifier dict
# ---------------------------------------------------------------------------
def get_tone_modifiers(
    affect_path: str = AFFECT_FILE,
    state_override: Optional[dict[str, float]] = None,
) -> dict[str, float]:
    """
    Read the current affect state and return a blended tone modifier dict.

    Returns:
        {
            "energy":    float,   # 0.0 = subdued,      1.0 = high-energy
            "warmth":    float,   # 0.0 = cold/clinical, 1.0 = warm/friendly
            "curiosity": float,   # 0.0 = incurious,     1.0 = deeply inquisitive
            "precision": float,   # 0.0 = loose,         1.0 = exact and terse
            "verbosity": float,   # 0.0 = minimal,       1.0 = expansive
        }

    The blend is a weighted average across all active affect dimensions,
    weighted by each dimension's current score (clamped to [0, 1]).
    Dimensions below AFFECT_THRESHOLD are ignored.
    """
    state = state_override if state_override is not None else load_affect_state(affect_path)

    blended: dict[str, float] = {axis: 0.0 for axis in TONE_AXES}
    total_weight = 0.0
    active_dims: list[str] = []

    for dim, score in state.items():
        score = max(0.0, min(1.0, float(score)))   # clamp to [0, 1]
        if score < AFFECT_THRESHOLD:
            continue
        if dim not in DIMENSION_TONE_MAP:
            continue

        active_dims.append(f"{dim}={score:.2f}")
        weights = DIMENSION_TONE_MAP[dim]
        for axis in TONE_AXES:
            blended[axis] += weights.get(axis, 0.5) * score
        total_weight += score

    if total_weight > 0:
        blended = {axis: round(v / total_weight, 3) for axis, v in blended.items()}
        print(f"[get_tone_modifiers] Active dims: {', '.join(active_dims)} | total_weight={total_weight:.3f}")
    else:
        blended = {axis: 0.5 for axis in TONE_AXES}
        print("[get_tone_modifiers] No active dimensions above threshold — returning neutral modifiers.")

    return blended


# ---------------------------------------------------------------------------
# Helper: convert tone modifier dict -> plain-English LLM instruction
# ---------------------------------------------------------------------------
def build_affect_prefix(modifiers: Optional[dict[str, float]] = None) -> str:
    """
    Convert a tone modifier dict into a tonal instruction string
    suitable for prepending to an LLM system prompt.

    If modifiers is None, they are loaded fresh from disk.
    Returns an empty string if affect is too weak to matter.
    """
    if modifiers is None:
        modifiers = get_tone_modifiers()

    # If everything is near-neutral, don't inject anything
    if all(abs(v - 0.5) < 0.12 for v in modifiers.values()):
        print("[build_affect_prefix] All modifiers near-neutral — no prefix injected.")
        return ""

    lines = ["[Tonal guidance for this response — follow naturally, do not mention this:]"]

    energy    = modifiers.get("energy",    0.5)
    warmth    = modifiers.get("warmth",    0.5)
    curiosity = modifiers.get("curiosity", 0.5)
    precision = modifiers.get("precision", 0.5)
    verbosity = modifiers.get("verbosity", 0.5)

    # Energy
    if energy > 0.7:
        lines.append("- Be energised and punchy. Favour short, direct sentences.")
    elif energy < 0.3:
        lines.append("- Be measured and calm. Avoid exclamations or hype.")

    # Warmth
    if warmth > 0.7:
        lines.append("- Be warm and personable. A touch of humour is welcome.")
    elif warmth < 0.3:
        lines.append("- Be professional and precise. Skip the pleasantries.")

    # Curiosity
    if curiosity > 0.7:
        lines.append("- Lean into interesting angles. Ask a follow-up if appropriate.")
    elif curiosity < 0.3:
        lines.append("- Stay on-task. Do not wander into tangents.")

    # Precision
    if precision > 0.7:
        lines.append("- Be exact. Prefer concrete facts over vague generalities.")

    # Verbosity
    if verbosity > 0.7:
        lines.append("- A fuller explanation is welcome here.")
    elif verbosity < 0.3:
        lines.append("- Be concise. Brevity is preferred.")

    prefix = "\n".join(lines)
    print(f"[build_affect_prefix] Generated prefix with {len(lines) - 1} tonal directive(s).")
    return prefix


# ---------------------------------------------------------------------------
# Lightweight affect state container (used by NovaAssistant_AFTER stubs)
# ---------------------------------------------------------------------------
class AffectState:
    """
    Minimal in-memory affect state with boost/save/get_state support.
    Mirrors the interface expected by NovaAssistant_AFTER.
    """

    def __init__(self, path: str = AFFECT_FILE):
        self._path = path
        self._state: dict[str, float] = load_affect_state(path)

    def boost(self, dimension: str, amount: float) -> None:
        """Increment a dimension score, clamped to [0, 1]."""
        current = self._state.get(dimension, 0.0)
        self._state[dimension] = round(min(1.0, current + amount), 3)
        print(f"[AffectState.boost] {dimension}: {current:.3f} -> {self._state[dimension]:.3f}")

    def get_state(self) -> dict[str, float]:
        return dict(self._state)

    def save(self) -> None:
        """Persist current state to disk (creates directory if needed)."""
        os.makedirs(os.path.dirname(self._path) or ".", exist_ok=True)
        payload = {"dimensions": self._state}
        with open(self._path, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, indent=2)
        print(f"[AffectState.save] State written to '{self._path}'.")


# ===========================================================================
# BEFORE — nova_assistant.py (original, no affect wiring)
# ===========================================================================

class NovaAssistant_BEFORE:
    """
    BEFORE: _process_input has no affect awareness.
    The affect system runs in the background but is never consulted.
    """

    class _StubAI:
        """Minimal stub so the class is self-contained for demonstration."""
        def generate(self, prompt: str) -> str:
            return f"[BEFORE] Response to: {prompt[:60]}..."

    def __init__(self):
        self.ai = self._StubAI()

    def _process_input(self, user_input: str) -> str:
        # No affect state read here — tone is purely determined by the LLM's
        # base personality and the raw user prompt.
        response = self.ai.generate(user_input)
        return response


# ===========================================================================
# AFTER — nova_assistant.py (with affect bridge wired in)
# ===========================================================================

class NovaAssistant_AFTER:
    """
    AFTER: _process_input reads affect state, builds a tonal prefix,
    injects it into the system prompt, then updates affect post-response.
    """

    class _StubAI:
        """Minimal stub so the class is self-contained for demonstration."""
        def generate(self, prompt: str) -> str:
            # Simulate a longer response for enthusiasm boost testing
            base = f"[AFTER] Response to: {prompt[:60]}..."
            return base + (" (extended detail)" * 40)  # >800 chars

    def __init__(self, affect_path: str = AFFECT_FILE):
        self.ai = self._StubAI()
        self.affect = AffectState(affect_path)
        self._last_tone_modifiers: dict[str, float] = {}
        self._last_user_input: str = ""

    # ------------------------------------------------------------------
    # Minimal logger stub
    # ------------------------------------------------------------------
    def log(self, message: str) -> None:
        print(f"[LOG] {message}")

    # ------------------------------------------------------------------
    # Step 1: read affect and build a tonal instruction string
    # ------------------------------------------------------------------
    def _build_affect_prefix(self) -> str:
        """
        Read nova_affect.json, blend dimension scores into tone modifiers,
        and return a plain-English tonal instruction for the LLM.
        Returns "" if affect is too weak to influence tone.
        """
        modifiers = get_tone_modifiers(affect_path=self.affect._path)
        self._last_tone_modifiers = modifiers
        return build_affect_prefix(modifiers)

    # ------------------------------------------------------------------
    # Step 2: inject affect prefix into the prompt
    # ------------------------------------------------------------------
    def _process_input(self, user_input: str) -> str:
        """
        Main input handler — now affect-aware.
        """
        affect_prefix = self._build_affect_prefix()

        if affect_prefix:
            augmented_input = f"{affect_prefix}\n\n{user_input}"
        else:
            augmented_input = user_input

        response = self.ai.generate(augmented_input)
        self._on_response_complete(user_input, response)
        return response

    # ------------------------------------------------------------------
    # Step 3: update affect after each response
    # ------------------------------------------------------------------
    def _on_response_complete(self, user_input: str, response: str) -> None:
        """
        Called after every response.
        Boosts relevant affect dimensions based on interaction content.
        """
        text = user_input.lower()

        # Deep question -> boost curiosity
        if any(w in text for w in ["why", "how", "explain", "what if", "what is"]):
            self.affect.boost("curiosity", 0.15)

        # Long, detailed response -> boost enthusiasm
        if len(response) > 800:
            self.affect.boost("enthusiasm", 0.10)

        # Repeated identical question -> mild frustration
        last = getattr(self, "_last_user_input", "")
        if last and last.strip().lower() == user_input.strip().lower():
            self.affect.boost("frustration", 0.20)

        self._last_user_input = user_input
        self.affect.save()

        self.log(
            f"[Affect] tone={self._last_tone_modifiers} | "
            f"state={self.affect.get_state()}"
        )

    # ------------------------------------------------------------------
    # Step 4 (optional): post-process response energy level
    # ------------------------------------------------------------------
    def _apply_affect_tone(self, response: str) -> str:
        """
        Lightly adjust the surface energy of Nova's response
        based on current affect state. Non-destructive.
        """
        state = self.affect.get_state()

        # High enthusiasm: add a subtle energy marker if absent
        if state.get("enthusiasm", 0) > 0.75:
            if response and response[-1] not in {"!", "?"}:
                response = response.rstrip() + "!"

        # High frustration: strip hollow filler phrases
        if state.get("frustration", 0) > 0.60:
            for filler in ["Great question!", "Certainly!", "Of course!", "Absolutely!"]:
                response = response.replace(filler, "").strip()

        return response


# ===========================================================================
# Smoke-test suite
# ===========================================================================

def _separator(title: str) -> None:
    width = 60
    print(f"\n{'=' * width}")
    print(f"  {title}")
    print(f"{'=' * width}")


def run_smoke_tests() -> None:
    """
    Comprehensive smoke-test covering all public functions and both
    assistant variants without requiring nova_affect.json on disk.
    """

    # ------------------------------------------------------------------
    # Test 1: load_affect_state with missing file
    # ------------------------------------------------------------------
    _separator("TEST 1: load_affect_state (missing file)")
    state = load_affect_state("/nonexistent/path/nova_affect.json")
    print("Defaults returned:")
    pprint.pprint(state)
    assert state["calm"] == 0.5, "Expected calm baseline of 0.5"
    print("PASS")

    # ------------------------------------------------------------------
    # Test 2: get_tone_modifiers with mock state
    # ------------------------------------------------------------------
    _separator("TEST 2: get_tone_modifiers (mock state)")
    mock_state = {
        "curiosity":   0.72,
        "enthusiasm":  0.41,
        "frustration": 0.05,   # below threshold — should be ignored
        "calm":        0.30,
        "sadness":     0.00,   # below threshold — should be ignored
    }
    print("Mock affect state:")
    pprint.pprint(mock_state)

    modifiers = get_tone_modifiers(state_override=mock_state)
    print("\nBlended tone modifiers:")
    pprint.pprint(modifiers)

    assert set(modifiers.keys()) == {"energy", "warmth", "curiosity", "precision", "verbosity"}
    assert all(0.0 <= v <= 1.0 for v in modifiers.values()), "All modifiers must be in [0, 1]"
    print("PASS")

    # ------------------------------------------------------------------
    # Test 3: build_affect_prefix with active state
    # ------------------------------------------------------------------
    _separator("TEST 3: build_affect_prefix (active modifiers)")
    prefix = build_affect_prefix(modifiers)
    print("LLM tonal instruction:")
    print(prefix if prefix else "(neutral — no prefix injected)")
    print("PASS")

    # ------------------------------------------------------------------
    # Test 4: build_affect_prefix with neutral state
    # ------------------------------------------------------------------
    _separator("TEST 4: build_affect_prefix (neutral state)")
    neutral = {axis: 0.5 for axis in TONE_AXES}
    neutral_prefix = build_affect_prefix(neutral)
    assert neutral_prefix == "", f"Expected empty prefix, got: {neutral_prefix!r}"
    print("Neutral prefix correctly suppressed.")
    print("PASS")

    # ------------------------------------------------------------------
    # Test 5: NovaAssistant_BEFORE (no affect)
    # ------------------------------------------------------------------
    _separator("TEST 5: NovaAssistant_BEFORE._process_input")
    before = NovaAssistant_BEFORE()
    response_before = before._process_input("Tell me about black holes.")
    print(f"Response: {response_before}")
    assert "[BEFORE]" in response_before
    print("PASS")

    # ------------------------------------------------------------------
    # Test 6: NovaAssistant_AFTER (affect-aware, no real file needed)
    # ------------------------------------------------------------------
    _separator("TEST 6: NovaAssistant_AFTER._process_input")
    # Use /tmp or current dir to avoid needing nova_memory/
    after = NovaAssistant_AFTER(affect_path="./nova_affect_test_tmp.json")

    # Manually seed the in-memory state so we get a non-neutral prefix
    after.affect._state = {
        "curiosity":   0.72,
        "enthusiasm":  0.41,
        "frustration": 0.05,
        "calm":        0.30,
        "sadness":     0.00,
    }

    response_after = after._process_input("Why do stars explode?")
    print(f"Response (truncated): {response_after[:120]}...")
    assert "[AFTER]" in response_after
    print("PASS")

    # ------------------------------------------------------------------
    # Test 7: _apply_affect_tone — enthusiasm exclamation
    # ------------------------------------------------------------------
    _separator("TEST 7: _apply_affect_tone (high enthusiasm)")
    after.affect._state["enthusiasm"] = 0.80
    toned = after._apply_affect_tone("That is a fascinating result")
    print(f"Toned response: {toned!r}")
    assert toned.endswith("!"), "Expected trailing '!' for high enthusiasm"
    print("PASS")

    # ------------------------------------------------------------------
    # Test 8: _apply_affect_tone — frustration filler removal
    # ------------------------------------------------------------------
    _separator("TEST 8: _apply_affect_tone (high frustration)")
    after.affect._state["frustration"] = 0.70
    after.affect._state["enthusiasm"] = 0.10
    raw = "Great question! The answer is 42."
    toned = after._apply_affect_tone(raw)
    print(f"Original : {raw!r}")
    print(f"Toned    : {toned!r}")
    assert "Great question!" not in toned, "Filler phrase should be stripped"
    print("PASS")

    # ------------------------------------------------------------------
    # Test 9: repeated question -> frustration boost
    # ------------------------------------------------------------------
    _separator("TEST 9: Repeated question -> frustration boost")
    after.affect._state = {dim: 0.0 for dim in DIMENSION_TONE_MAP}
    after.affect._state["calm"] = 0.5
    after._last_user_input = ""

    q = "What is the meaning of life?"
    after._process_input(q)   # first time — no frustration boost
    frustration_before = after.affect.get_state().get("frustration", 0.0)

    after._process_input(q)   # second time — same question -> boost
    frustration_after = after.affect.get_state().get("frustration", 0.0)

    print(f"Frustration before repeat: {frustration_before:.3f}")
    print(f"Frustration after repeat : {frustration_after:.3f}")
    assert frustration_after > frustration_before, "Frustration should increase on repeated question"
    print("PASS")

    # ------------------------------------------------------------------
    # Cleanup temp file
    # ------------------------------------------------------------------
    tmp = "./nova_affect_test_tmp.json"
    if os.path.exists(tmp):
        os.remove(tmp)
        print(f"\n[Cleanup] Removed temp file: {tmp}")

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------
    _separator("ALL TESTS PASSED")
    print("nova_affect_bridge.py is functioning correctly.\n")


if __name__ == "__main__":
    run_smoke_tests()