# Generated: 2026-04-08 16:19:00
# ============================================================

# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-04-08 16:19:00
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt
def average(nums):
    if not nums:
        raise ValueError("Cannot compute average of an empty list — no data provided.")
    return sum(nums) / len(nums)

# Test 1: Empty list
try:
    result = average([])
    print(f"average([]) = {result}")
except ValueError as e:
    print(f"average([]) raised ValueError: {e}")

# Test 2: Non-empty list
result = average([1, 2, 3, 4, 5])
print(f"average([1, 2, 3, 4, 5]) = {result}")

# Test 3: Single element
result = average([42])
print(f"average([42]) = {result}")

# Test 4: Floats
result = average([1.5, 2.5, 3.0])
print(f"average([1.5, 2.5, 3.0]) = {result}")

# Test 5: Negative numbers
result = average([-10, -20, -30])
print(f"average([-10, -20, -30]) = {result}")