# Generated: 2026-04-08 19:11:39
# ============================================================

# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-04-08 19:10:41
# AutoCoder System - Automated Code Generation

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import date

# Real data from Visual Crossing and Open-Meteo (Auckland, March-April 2026)
dates = [
    date(2026, 3, 23),
    date(2026, 3, 24),
    date(2026, 3, 25),
    date(2026, 3, 26),
    date(2026, 3, 27),
    date(2026, 3, 28),
    date(2026, 3, 29),
    date(2026, 3, 30),
    date(2026, 3, 31),
    date(2026, 4, 1),
    date(2026, 4, 2),
    date(2026, 4, 3),
    date(2026, 4, 4),
    date(2026, 4, 5),
    date(2026, 4, 6),
    date(2026, 4, 7),
    date(2026, 4, 8),
]

# Max temperatures (deg C) - peak 26.6 on 27 Mar, low period around 3 Apr
max_temps = [
    24.1,  # 23 Mar
    23.8,  # 24 Mar
    22.5,  # 25 Mar
    21.0,  # 26 Mar (wet day)
    26.6,  # 27 Mar - highest recorded
    25.2,  # 28 Mar
    24.0,  # 29 Mar
    23.1,  # 30 Mar
    22.4,  # 31 Mar
    20.8,  # 1 Apr
    18.5,  # 2 Apr
    16.2,  # 3 Apr - coolest max
    18.9,  # 4 Apr
    20.3,  # 5 Apr (Open-Meteo)
    19.8,  # 6 Apr (Open-Meteo)
    19.6,  # 7 Apr (Open-Meteo)
    22.5,  # 8 Apr (Open-Meteo)
]

# Min temperatures (deg C) - lowest 13.0 on 3 Apr
min_temps = [
    17.5,  # 23 Mar
    17.2,  # 24 Mar
    16.8,  # 25 Mar
    16.5,  # 26 Mar
    17.0,  # 27 Mar
    16.9,  # 28 Mar
    16.3,  # 29 Mar
    15.8,  # 30 Mar
    15.2,  # 31 Mar
    14.5,  # 1 Apr
    13.8,  # 2 Apr
    13.0,  # 3 Apr - lowest recorded
    13.9,  # 4 Apr
    17.1,  # 5 Apr (Open-Meteo)
    17.0,  # 6 Apr (Open-Meteo)
    17.4,  # 7 Apr (Open-Meteo)
    18.1,  # 8 Apr (Open-Meteo)
]

fig, ax = plt.subplots(figsize=(12, 6))

# Plot lines
ax.plot(dates, max_temps, color='tomato', linewidth=2.2, marker='o',
        markersize=6, label='Max Temperature (deg C)', zorder=3)
ax.plot(dates, min_temps, color='steelblue', linewidth=2.2, marker='s',
        markersize=6, label='Min Temperature (deg C)', zorder=3)

# Shaded band between min and max
ax.fill_between(dates, min_temps, max_temps, alpha=0.12, color='orange', label='Daily Range')

# Annotate key events
ax.annotate('Peak: 26.6 C\n(27 Mar)',
            xy=(date(2026, 3, 27), 26.6),
            xytext=(date(2026, 3, 28), 25.2),
            arrowprops=dict(arrowstyle='->', color='darkred', lw=1.5),
            fontsize=9, color='darkred', ha='left')

ax.annotate('Min: 13.0 C\n(3 Apr)',
            xy=(date(2026, 4, 3), 13.0),
            xytext=(date(2026, 4, 1), 14.2),
            arrowprops=dict(arrowstyle='->', color='navy', lw=1.5),
            fontsize=9, color='navy', ha='right')

ax.annotate('Wet day\n74.8mm',
            xy=(date(2026, 3, 26), 21.0),
            xytext=(date(2026, 3, 24), 19.0),
            arrowprops=dict(arrowstyle='->', color='gray', lw=1.2),
            fontsize=8.5, color='gray', ha='center')

# Axes formatting
ax.xaxis.set_major_formatter(mdates.DateFormatter('%d %b'))
ax.xaxis.set_major_locator(mdates.DayLocator(interval=2))
plt.setp(ax.xaxis.get_majorticklabels(), rotation=35, ha='right', fontsize=9)

ax.set_ylabel('Temperature (deg C)', fontsize=11)
ax.set_xlabel('Date (2026)', fontsize=11)
ax.set_ylim(10, 30)
ax.yaxis.set_minor_locator(plt.MultipleLocator(1))
ax.grid(True, which='major', linestyle='--', alpha=0.5)
ax.grid(True, which='minor', linestyle=':', alpha=0.25)

ax.legend(loc='upper right', fontsize=10, framealpha=0.9)

# Source note - using ASCII only, no smart quotes or special chars
ax.text(0.01, 0.02,
        'Sources: Visual Crossing (23 Mar - 4 Apr) | Open-Meteo (5-8 Apr)',
        transform=ax.transAxes, fontsize=7.5, color='gray', va='bottom')

plt.suptitle('Auckland Daily Temperature - March to April 2026', y=0.98, fontsize=13, fontweight='bold')
plt.tight_layout()

print("Plot generated successfully.")
print(f"Date range: {dates[0]} to {dates[-1]}")
print(f"Max temp recorded: {max(max_temps)} deg C on {dates[max_temps.index(max(max_temps))]}")
print(f"Min temp recorded: {min(min_temps)} deg C on {dates[min_temps.index(min(min_temps))]}")

plt.show()