# Generated: 2026-04-08 19:06:25
# ============================================================

# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-04-08 19:06:25
# AutoCoder System - Automated Code Generation

import control as ctrl
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import toeplitz

# Reproducibility
rng = np.random.default_rng(42)

# Parameters
N        = 512          # number of samples
M        = 16           # Wiener filter order (causal, FIR)
snr_db   = 10.0         # desired SNR in dB
ar_coeff = 0.85         # AR(1) pole

# 1. Generate desired signal: AR(1) process
# x[n] = ar_coeff * x[n-1] + w[n],  w ~ N(0, sigma_w^2)
sigma_w  = 1.0
x = np.zeros(N)
w = rng.normal(0, sigma_w, N)
for n in range(1, N):
    x[n] = ar_coeff * x[n - 1] + w[n]

# 2. Add white Gaussian noise to form observed signal
signal_power = np.var(x)
snr_linear   = 10 ** (snr_db / 10.0)
noise_var    = signal_power / snr_linear
sigma_v      = np.sqrt(noise_var)
v            = rng.normal(0, sigma_v, N)
y            = x + v          # noisy observation

# 3. Compute autocorrelation of observed signal (Ryy)
# For WSS: Ryy[k] = Rxx[k] + Rvv[k]
# AR(1) autocorrelation: Rxx[k] = sigma_w^2 / (1 - ar_coeff^2) * ar_coeff^|k|
sigma_x2 = sigma_w**2 / (1 - ar_coeff**2)   # variance of x

lags     = np.arange(M)
Rxx_lags = sigma_x2 * ar_coeff ** lags       # Rxx[0..M-1]
Rvv_lags = np.zeros(M)
Rvv_lags[0] = noise_var                      # white noise: only lag-0 term

Ryy_lags = Rxx_lags + Rvv_lags              # autocorrelation of y

# 4. Compute cross-correlation of desired & observed (Rxy)
# Rxy[k] = E[x[n] y[n-k]] = Rxx[k]  (v independent)
Rxy_lags = Rxx_lags.copy()                  # shape (M,)

# 5. Solve Wiener-Hopf equations: Ryy * h = Rxy
Ryy_matrix = toeplitz(Ryy_lags)             # M x M Toeplitz autocorrelation matrix
h_wiener   = np.linalg.solve(Ryy_matrix, Rxy_lags)

# 6. Apply Wiener filter (causal convolution)
x_hat = np.convolve(y, h_wiener, mode='full')[:N]

# 7. Compute metrics
# Trim transient (first M-1 samples)
trim = M - 1
x_t     = x[trim:]
y_t     = y[trim:]
xhat_t  = x_hat[trim:]

mse_noisy  = np.mean((x_t - y_t)  ** 2)
mse_wiener = np.mean((x_t - xhat_t) ** 2)

snr_in  = 10 * np.log10(np.var(x_t) / np.var(x_t - y_t))
snr_out = 10 * np.log10(np.var(x_t) / np.var(x_t - xhat_t))

# 8. Plot
t = np.arange(N)

fig, axes = plt.subplots(3, 1, figsize=(12, 9), sharex=True)

axes[0].plot(t, x, color='steelblue', lw=1.2, label='Desired signal x[n]')
axes[0].set_ylabel('Amplitude')
axes[0].set_title('Desired Signal  (AR(1) process, pole = {:.2f})'.format(ar_coeff))
axes[0].legend(loc='upper right')
axes[0].grid(True, alpha=0.35)

axes[1].plot(t, y, color='tomato', lw=0.8, alpha=0.85,
             label='Noisy observation y[n]  (SNR = {:.1f} dB,  MSE = {:.4f})'.format(snr_in, mse_noisy))
axes[1].set_ylabel('Amplitude')
axes[1].set_title('Noisy Observation  (AWGN added, SNR_in = {:.1f} dB)'.format(snr_in))
axes[1].legend(loc='upper right')
axes[1].grid(True, alpha=0.35)

axes[2].plot(t, x,     color='steelblue', lw=1.0, alpha=0.5, label='Desired x[n]')
axes[2].plot(t, x_hat, color='darkorange', lw=1.3,
             label='Wiener filter output  (SNR = {:.1f} dB,  MSE = {:.4f})'.format(snr_out, mse_wiener))
axes[2].set_ylabel('Amplitude')
axes[2].set_xlabel('Sample index n')
axes[2].set_title('Wiener Filter Output  (order M = {},  SNR_out = {:.1f} dB)'.format(M, snr_out))
axes[2].legend(loc='upper right')
axes[2].grid(True, alpha=0.35)

plt.suptitle(
    'Stochastic Wiener Filter Simulation  |  '
    'Wiener-Hopf (Autocorrelation Matrix Method)  |  '
    'SNR improvement: {:.1f} dB'.format(snr_out - snr_in),
    y=0.98, fontsize=12, fontweight='bold'
)

plt.tight_layout()
plt.show()

# Console summary
print("=" * 55)
print("  Stochastic Wiener Filter - Results Summary")
print("=" * 55)
print(f"  Filter order M        : {M}")
print(f"  AR(1) pole            : {ar_coeff}")
print(f"  Target SNR            : {snr_db:.1f} dB")
print(f"  Input  SNR            : {snr_in:.2f} dB")
print(f"  Output SNR            : {snr_out:.2f} dB")
print(f"  SNR improvement       : {snr_out - snr_in:.2f} dB")
print(f"  MSE (noisy)           : {mse_noisy:.6f}")
print(f"  MSE (Wiener output)   : {mse_wiener:.6f}")
print(f"  MSE reduction factor  : {mse_noisy / mse_wiener:.2f}x")
print("=" * 55)