# Generated: 2026-04-24 13:15:56
# ============================================================

# Generated by: anthropic/claude-sonnet-4-6 (Cloud)
# Date: 2026-04-24 13:15:41
# AutoCoder System - Automated Code Generation

import numpy as np
import matplotlib.pyplot as plt

# Define the range
x = np.linspace(-10, 10, 1000)

# Antiderivative of x^2 * cos(x):
# F(x) = 2x*cos(x) + (x^2 - 2)*sin(x) + C
C = 0  # constant of integration set to 0
F = 2*x*np.cos(x) + (x**2 - 2)*np.sin(x) + C

# Plot
fig, ax = plt.subplots(figsize=(10, 6))

ax.plot(x, F, color='royalblue', linewidth=2,
        label=r'$F(x) = 2x\cos(x) + (x^2 - 2)\sin(x) + C$')

ax.axhline(0, color='black', linewidth=0.8, linestyle='--', alpha=0.5)
ax.axvline(0, color='black', linewidth=0.8, linestyle='--', alpha=0.5)

ax.set_xlabel(r'$x$', fontsize=13)
ax.set_ylabel(r'$F(x)$', fontsize=13)
ax.set_title(r'Antiderivative of $x^2\cos(x)$', fontsize=15)

ax.legend(fontsize=11, loc='upper left')
ax.grid(True, alpha=0.3)
ax.set_xlim(-10, 10)

# Annotate the integrand
ax.annotate(
    r'$\int x^2 \cos(x)\, dx = 2x\cos(x) + (x^2 - 2)\sin(x) + C$',
    xy=(0.5, 0.05),
    xycoords='axes fraction',
    ha='center',
    fontsize=11,
    bbox=dict(boxstyle='round,pad=0.4', facecolor='lightyellow', edgecolor='gray', alpha=0.8)
)

plt.tight_layout()
print("Plot rendered: Antiderivative of x^2 * cos(x)")
print(f"F(x) range over [-10, 10]: min={F.min():.2f}, max={F.max():.2f}")
plt.show()